version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-lms
    container_name: laravel-lms-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./database:/var/www/database
    ports:
      - "8080:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
